### ISSUE TITLE
Trying to export anything but the App provides an empty csv file

### ISSUE THREAD

**Issue by fnielsontestout** [Erudika/para-admin-ui#3]
I'm unable to export questions, replies, etc, to a csv file. It always creates an empty csv.

![image](https://user-images.githubusercontent.com/48336978/54364876-65ff0900-4633-11e9-87d6-31cd44341848.png)

**Comment by albogdano** [comment]
It seems to be a problem with ng-admin. I couldn't figure it out, sorry. It's best to use the `para-cli` tool for exporting data anyway.

**Comment by fnielsontestout** [comment]
I see. Thanks for your help!
