### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by utkarshsystem** [Erudika/para-admin-ui#9]
Class `java.util.ArrayList` not subtype of `java.util.Map<java.lang.String,java.util.List<java.lang.String>>` (through reference chain: java.util.HashMap[\"items\"]->java.util.ArrayList[3]->com.erudika.para.core.App[\"resourcePermissions\"])"

**Comment by albogdano** [comment]
Hi, where do you see that error - Para logs or browser dev console? Does it happen on update or on read?

**Comment by utkarshsystem** [comment]
I see the error on the console browser when I click on apps. Our Developer try to put some roles and looks like he injected bad data

**Comment by utkarshsystem** [comment]
![image](https://user-images.githubusercontent.com/1451615/165410576-fc4f63ae-eae5-4128-a7db-382022a211f5.png)

**Comment by albogdano** [comment]
What is the value that was submitted for `app.resourcePermissions`?

**Comment by albogdano** [comment]
Fixed in latest Para `1.45.9`. Thanks for reporting the bug!

**Comment by virtusavivek** [comment]
Just now I checked it. Still, I'm getting the same issue. Please help me to resolve the issue.
Thanks
![image](https://user-images.githubusercontent.com/79599701/166109929-71d9e01d-6219-4806-8934-0c846725fef9.png)

**Comment by albogdano** [comment]
Did you update Para to the latest version? Did you also try to disconnect, do a hard refresh and connect again?

**Comment by albogdano** [comment]
If the problem persists, update the app object through the API: `PATCH /v1/apps/app:para` with the payload:
```
{"resourcePermissions": {}}
```
and then try again.
